services:
  app:
    build: .
    container_name: nest-app
    ports:
      - "3001:8000"
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules  # закоментовано на Windows
    command: yarn start
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
