services:
  app:
    build: .
    container_name: nest-app
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules  # закоментовано на Windows
    command: yarn start:dev
    restart: always
    depends_on:
      - db
  # environment:
  #     DATABASE_URL: postgresql://user:password@localhost:5432/nestdb?schema=public


  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
